const Router = require("express");
const router = new Router();
const authRoutes = require("./authRoutes");
const todoRoutes = require("./todoRoutes");
const schoolRoutes = require("./schoolRoutes.js/schoolRoutes");
const studentRoutes = require("./studentRoutes/studentRoutes");
const parentRoutes = require("./parentRoutes/parentRoutes");
const journeyRoutes = require("./journeyRoutes/journeyRoutes");
const luggageRoutes = require("./luggageRoutes/luggageRoutes");
const vehicleTypeRoutes = require("./vehiculeTyoeRoutes/vehiculeTypeRoutes");
const passengerLuggageLimitsIdRoutes = require("./passengerLuggageLimitsRoutes/passengerLuggageLimitsRoutes");
const affiliateRoutes = require("./affiliateRoutes/affiliateRoutes");
const complainRoutes = require("./complainRoutes/complainRoutes");
const sourceRoutes = require("./sourceRoutes/sourceRoutes");
const visitorFeedbackRoutes = require("./visitorFeedbackRoutes/visitorFeedbackRoutes");
const visitorRoutes = require("./visitorRoutes/visitorRoutes");
const emailTemplateRoutes = require("./emailTemplateRoutes/emailTemplateRoutes");
const quoteRoutes = require("./quoteRoutes/quoteRoutes");
const noteRoutes = require("./noteRoutes/noteRoutes");
const vehicleRoutes = require("./vehicleRoutes/vehicleRoutes");
const driverRoutes = require("./driverRoutes/driverRoutes");
const luxuryRoutes = require("./luxuryRoutes/luxuryRoutes");
const mileageBandRoutes = require("./mileageBandRoutes/mileageBandRoutes");
const hourlyBandRoutes = require("./hourlyBandRoutes/hourlyBandRoutes");
const waitingBandRoutes = require("./waitingBandRoutes/waitingBandRoutes");
const stopRoutes = require("./stopRoutes/stopRoutes");
const companyRoutes = require("./companyRoutes/companyRoutes");
const teamRoutes = require("./teamRoutes/teamRoutes");
const authCentralAppRoutes = require("./authCentralAppRoutes/authCentralAppRoutes");
const employeesRoutes = require("./employeeRoutes/employeeRoutes");
const employeeAttendanceRoutes = require("./employeeAttendanceRoutes/employeeAttendanceRoutes");
const studentAttendanceRoutes = require("./studentAttendanceRoutes/studentAttendanceRoute");
const groupEmployeeRoutes = require("./groupCompanyRoutes/groupCompanyRoutes");
const pricingCalendarRoutes = require("./pricingCalendarRoutes/pricingCalendarRoute");
const modeRoutes = require("./modeRoutes/modeRoutes");
const regionalPricingRoutes = require("./regionalPricingRoutes/regionalPricingRoutes");
const locationRoutes = require("./locationRoutes/locationRoutes");
const pricingPostalCodeRoutes = require("./pricingPostalCodeRoutes/pricingPostalCodeRoutes");
const forceSingleRoutes = require("./forceSingleRoutes/forceSingleRoutes");
const programmRoutes = require("./programmRoutes/programmRoutes");
const contractRoutes = require("./contractRoutes/contractRoutes");
const checkTypeRoutes = require("./checkTypeRoutes/checkTypeRoutes");
const checkListRoutes = require("./checkListRoutes/checkListRoutes");
const affiliateVehicleRoutes = require("./affiliateVehicleRoutes/affiliateVehicleRoutes");
const affiliateDriverRoutes = require("./affiliateDriverRoutes/affiliateDriverRoutes");
const attachmentRoutes = require("./attachmentRoutes/attachmentRoutes");
const emailSentRoutes = require("./emailSentRoutes/emailSentRoutes");
const feedbackRoutes = require("./feedbackRoutes/feedbackRoutes");
const shortCodeRoutes = require("./shortCodeRoutes/shortCodeRoutes");
const emailQueueRoutes = require("./emailQueueRoutes/emailQueueRoutes");
const groupRoutes = require("./groupSchoolRoutes/groupSchoolRoutes");
const rejectedJobsRoutes = require("./rejectedJobsByAffiliateRoutes/rejectedJobsByAffiliateRoutes");
const passwordResetVerifCodeRoutes = require("./passwordResetVerificationCodeRoutes/passwordResetVerificationCodeRoutes");
const visitorPaymentTrackingRoutes = require("./visitorPaymentTrackingRoutes/visitorPaymentTrackingRoutes");
const qrCodeRoutes = require("./qrCodeRoutes/qrCodeRoutes");
const defectRoutes = require("./defectRoutes/defectRoutes");
const requestFeatureRoutes = require("./requestFeatureRoutes/requestFeatureRoutes");
const errorReportRoutes = require("./errorReportRoutes/errorReportRoutes");
const headerRoutes = require("./headerRoutes/headerRoutes");
const menuRoutes = require("./menuRoutes/menuRoutes");
const footerListRoutes = require("./footerListRoutes/footerListRoutes");
const pageRoutes = require("./pageRoutes/pageRoutes");
const footerSocialRoutes = require("./footerSocialRoutes/footerSocialRoutes");
const aboutUsComponentRoutes = require("./aboutUsComponentRoutes/aboutUsComponentRoutes");
const ourValueComponentRoutes = require("./ourValueComponentRoutes/ourValueComponentRoutes");
const offerServicesRoutes = require("./offerServicesRoutes/offerServicesRoutes");
const iconRoutes = require("./iconRoutes/iconRoutes");
const htmlPageRoutes = require("./htmlPageRoutes/htmlPageRoutes");
const ourMissionRoutes = require("./ourMissionRoutes/ourMissionRoutes");
const socialServicesRoutes = require("./socialServicesRoutes/socialServicesRoutes");
const bestOfferComponentRoutes = require("./bestOfferComponentRoutes/bestOfferComponentRoutes");
const servicesBlock1ComponentRoutes = require("./servicesBlock1ComponentRoutes/servicesBlock1ComponentRoutes");
const vehicleGuideRoutes = require("./vehicleGuideComponentRoutes/vehicleGuideComponentRoutes");
const vehiclesClassRoutes = require("./vehiclesClassComponentRoutes/vehiclesClassComponentRoutes");
const fleetRoutes = require("./fleetComponentRoutes/fleetComponentRoutes");
const onTheRoadRoutes = require("./onTheRoadComponentRoutes/onTheRoadComponentRoutes");
const inThePressRoutes = require("./inThePressComponentRoutes/inThePressComponentRoutes");
const notificationRoutes = require("./notificationRoutes/notificationRoutes");
const termsConditionComponentRoutes = require("./termsConditionComponentRoutes/termsConditionComponentRoutes");
const appRoutes = require("./appRoutes/appRoutes");
const offerRoutes = require("./offerRoutes/offerRoutes");

router.use("/authSchool", schoolRoutes);
router.use("/student", studentRoutes);
router.use("/parent", parentRoutes);

router.use("/journey", journeyRoutes);

router.use("/luggage", luggageRoutes);

router.use("/vehicleType", vehicleTypeRoutes);

router.use("/passengerLuggageLimit", passengerLuggageLimitsIdRoutes);

/// FOR TEST ONLY ///
router.use("/auth", authRoutes);
router.use("/todos", todoRoutes);

/// BCT APIS ///
router.use("/emailQueue", emailQueueRoutes);
router.use("/feedback", feedbackRoutes);
router.use("/attachment", attachmentRoutes);
router.use("/emailSent", emailSentRoutes);
router.use("/affiliate", affiliateRoutes);
router.use("/complains", complainRoutes);
router.use("/source", sourceRoutes);
router.use("/visitor-feedback", visitorFeedbackRoutes);
router.use("/visitor", visitorRoutes);
router.use("/emailTemplate", emailTemplateRoutes);
router.use("/quote", quoteRoutes);
router.use("/notes", noteRoutes);
router.use("/vehicle", vehicleRoutes);
router.use("/driver", driverRoutes);
router.use("/vehicleExtraLuxurys", luxuryRoutes);
router.use("/mileageBand", mileageBandRoutes);
router.use("/hourlyBand", hourlyBandRoutes);
router.use("/waitingBand", waitingBandRoutes);
router.use("/stop", stopRoutes);
router.use("/companies", companyRoutes);
router.use("/team", teamRoutes);
router.use("/authCentralApp", authCentralAppRoutes);
router.use("/employees", employeesRoutes);
router.use("/employeeAttendance", employeeAttendanceRoutes);
router.use("/studentAttendance", studentAttendanceRoutes);
router.use("/groupEmployee", groupEmployeeRoutes);
router.use("/pricingCalendar", pricingCalendarRoutes);
router.use("/mode", modeRoutes);
router.use("/regionalPricing", regionalPricingRoutes);
router.use("/location", locationRoutes);
router.use("/pricingPostalCode", pricingPostalCodeRoutes);
router.use("/forceSingle", forceSingleRoutes);
router.use("/programm", programmRoutes);
router.use("/contract", contractRoutes);
router.use("/duty-check", checkTypeRoutes);
router.use("/check-list", checkListRoutes);
router.use("/affiliateVehicle", affiliateVehicleRoutes);
router.use("/affiliateDriver", affiliateDriverRoutes);
router.use("/shortCode", shortCodeRoutes);
router.use("/groupStudent", groupRoutes);
router.use("/rejectedJobs", rejectedJobsRoutes);
router.use("/password", passwordResetVerifCodeRoutes);
router.use("/visitor-payment", visitorPaymentTrackingRoutes);
router.use("/qr-code", qrCodeRoutes);
router.use("/defects", defectRoutes);
router.use("/request-feature", requestFeatureRoutes);
router.use("/error-report", errorReportRoutes);
router.use("/header", headerRoutes);
router.use("/menu", menuRoutes);
router.use("/footer-list", footerListRoutes);
router.use("/pages", pageRoutes);
router.use("/footer-social", footerSocialRoutes);
router.use("/about-us-component", aboutUsComponentRoutes);
router.use("/our-value-component", ourValueComponentRoutes);
router.use("/offre-service-component", offerServicesRoutes);
router.use("/icons", iconRoutes);
router.use("/html-pages", htmlPageRoutes);
router.use("/our-mission-component", ourMissionRoutes);
router.use("/social-services-component", socialServicesRoutes);
router.use("/best-offers-component", bestOfferComponentRoutes);
router.use("/services-block1-component", servicesBlock1ComponentRoutes);
router.use("/vehicle-guide-component", vehicleGuideRoutes);
router.use("/vehicles-class-component", vehiclesClassRoutes);
router.use("/fleets-component", fleetRoutes);
router.use("/on-the-road-component", onTheRoadRoutes);
router.use("/in-the-press-component", inThePressRoutes);
router.use("/notifications", notificationRoutes);
router.use("/terms-condition", termsConditionComponentRoutes);
router.use("/application", appRoutes);
router.use("/offer", offerRoutes);

module.exports = router;
